# Generated by Django 2.0 on 2019-02-25 18:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web_statistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayLookNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=django.utils.timezone.now, verbose_name='日期')),
                ('count', models.IntegerField(default=0, verbose_name='总阅读量')),
            ],
            options={
                'verbose_name': '总阅读量',
                'verbose_name_plural': '总阅读量',
            },
        ),
    ]
