# Generated by Django 2.0 on 2019-04-27 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_statistics', '0002_daylooknumber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daylooknumber',
            options={'verbose_name': '单日总阅读量', 'verbose_name_plural': '单日总阅读量'},
        ),
    ]
