# Generated by Django 2.0 on 2019-02-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190221_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='YuKalix', max_length=32, verbose_name='文章作者'),
            preserve_default=False,
        ),
    ]
