# Generated by Django 2.0 on 2019-02-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190223_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(default='YuKalix', max_length=32, verbose_name='文章作者'),
        ),
        migrations.AlterField(
            model_name='article',
            name='intro',
            field=models.CharField(default='', max_length=300, verbose_name='文章简介'),
        ),
    ]
