# Generated by Django 2.0 on 2019-02-20 16:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMeArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='文章标题')),
                ('article', ckeditor.fields.RichTextField(blank=True, verbose_name='文章')),
            ],
            options={
                'verbose_name': '关于我信息',
                'verbose_name_plural': '关于我信息',
            },
        ),
        migrations.CreateModel(
            name='AboutMeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_portrait', models.ImageField(blank=True, upload_to='about_me/', verbose_name='头像')),
                ('nick_name', models.CharField(default='YuKalix', max_length=32, verbose_name='昵称')),
                ('name', models.CharField(default='羽', max_length=32, verbose_name='姓名')),
                ('work', models.CharField(default='Python全栈开发工程师', max_length=32, verbose_name='工作')),
                ('place', models.CharField(default='杭州', max_length=32, verbose_name='地点')),
                ('email', models.EmailField(default='dong.guowei@aliyun.com', max_length=254, verbose_name='邮箱')),
                ('record_tip', models.CharField(max_length=32, verbose_name='点滴语录')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '关于我信息',
                'verbose_name_plural': '关于我信息',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_imamge', models.ImageField(blank=True, upload_to='banners/%Y/%m', verbose_name='图片')),
                ('baner_describe', models.CharField(default='广告位招租', max_length=32, verbose_name='图片描述')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '主页Banner',
                'verbose_name_plural': '主页Banner',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_photo', models.URLField(default='/media/message/users/2019/02/20/tx2.jpg', verbose_name='用户头像')),
                ('user_name', models.CharField(max_length=32, verbose_name='用户名')),
                ('message', models.CharField(max_length=126, verbose_name='留言')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言',
            },
        ),
        migrations.CreateModel(
            name='MessageUserPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_photo', models.ImageField(upload_to='message/users/%Y/%m/%d', verbose_name='用户头像')),
            ],
            options={
                'verbose_name': '留言头像',
                'verbose_name_plural': '留言头像',
            },
        ),
    ]
