# Generated by Django 2.0 on 2019-02-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_portrait', models.ImageField(blank=True, upload_to='about_me/', verbose_name='头像')),
                ('nick_name', models.CharField(default='YuKalix', max_length=32, verbose_name='昵称')),
                ('name', models.CharField(default='羽', max_length=32, verbose_name='姓名')),
                ('work', models.CharField(default='Python全栈开发工程师', max_length=32, verbose_name='工作')),
                ('place', models.CharField(default='杭州', max_length=32, verbose_name='地点')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('recor_tip', models.CharField(max_length=32, verbose_name='点滴语录')),
            ],
            options={
                'verbose_name': '关于我信息',
                'verbose_name_plural': '关于我信息',
            },
        ),
    ]
