# Generated by Django 2.0 on 2019-02-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='articles/%Y/%m/%d', verbose_name='文章配图'),
        ),
    ]
