# Generated by Django 2.0 on 2019-02-19 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_aboutmeinfo_add_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutmeinfo',
            old_name='recor_tip',
            new_name='record_tip',
        ),
    ]
