# Generated by Django 2.0 on 2019-02-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190219_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_imamge', models.ImageField(blank=True, upload_to='banners/%Y/%M', verbose_name='图片')),
                ('baner_describe', models.CharField(default='广告位招租', max_length=32, verbose_name='图片描述')),
            ],
            options={
                'verbose_name': '关于我信息',
                'verbose_name_plural': '关于我信息',
            },
        ),
    ]
