# Generated by Django 2.0 on 2019-02-19 19:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='时间'),
            preserve_default=False,
        ),
    ]
