# Generated by Django 2.0 on 2019-02-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='recommend',
            field=models.BooleanField(default=0, verbose_name='特别推荐'),
        ),
    ]
