# Generated by Django 2.0 on 2019-02-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_banner_add_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_photo', models.ImageField(upload_to='message/users/%Y/%m/%d', verbose_name='用户头像')),
                ('user_name', models.CharField(max_length=32, verbose_name='用户名')),
                ('message', models.CharField(max_length=126, verbose_name='留言')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言',
            },
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '主页Banner', 'verbose_name_plural': '主页Banner'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_imamge',
            field=models.ImageField(blank=True, upload_to='banners/%Y/%m', verbose_name='图片'),
        ),
    ]
