# Generated by Django 2.0 on 2019-02-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_is_original'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareRecourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='resourse/%Y/%m/%d', verbose_name='资源图片')),
                ('name', models.CharField(max_length=64, verbose_name='资源名字')),
                ('intro', models.CharField(max_length=300, verbose_name='资源介绍')),
                ('path', models.URLField(default='', verbose_name='资源链接')),
                ('passwd', models.CharField(blank=True, max_length=10, verbose_name='资源密码')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '资源',
                'verbose_name_plural': '资源',
            },
        ),
    ]
