# Generated by Django 2.0 on 2019-02-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190220_0056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messageuserphoto',
            options={'verbose_name': '留言头像', 'verbose_name_plural': '留言头像'},
        ),
        migrations.AlterField(
            model_name='message',
            name='user_photo',
            field=models.URLField(default='/media/message/users/2019/02/20/tx2.jpg', verbose_name='用户头像'),
        ),
    ]
